name: Build Vue
on:
  push:
    branches:
      - master
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Electron App
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: install node
        uses: actions/setup-node@master
      - name: Install dependencies
        run: npm install
      - name: Build
        run:  npm run win-build
